#!/bin/bash

set -e

rm -rf /etc/apt/sources.list.d
echo deb http://mirrors.cloud.aliyuncs.com/debian buster main > /etc/apt/sources.list
echo deb http://mirrors.cloud.aliyuncs.com/debian-security buster/updates main >> /etc/apt/sources.list
echo deb http://mirrors.cloud.aliyuncs.com/debian buster-updates main >> /etc/apt/sources.list

if [ ! -d "/tmp/install" ]
then
  mkdir -p /tmp/install/root
else
  rm -rf /tmp/install
  mkdir -p /tmp/install/root
fi

current_dir=$(pwd)

if [ ! -d "$current_dir/apt-archives" ]
then
  mkdir -p "$current_dir/apt-archives"
else
  rm -rf "$current_dir/apt-archives"
  mkdir -p "$current_dir/apt-archives"
fi

apt-get update && apt-get install -y -d -o=dir::cache=/tmp/install $* --reinstall --no-install-recommends

for f in $(ls /tmp/install/archives/*.deb); do \
  echo "Preparing to unpack ${f##*/}"; \
  cd /tmp/install/archives; \
  dpkg-deb -x ${f##*/} $current_dir/apt-archives; \
done;
